language: c
compiler:
  - gcc
  - clang

env:
  - PLATFORM=posix TESTS=yes
  - PLATFORM=contiki

addons:
  apt_packages:
    - libcunit1-dev
    - doxygen
    - libxml2-utils
    - xsltproc
    - docbook-xml
    - asciidoc

branches:
  only:
     - master
     - develop
     - /^release-.*$/

before_script: ./autogen.sh --clean && ./autogen.sh

script: scripts/build.sh
